name: Deploy Project

on:
  push:
    branches: [ master ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Build Website
        run: |
          cd website
          npm install
          npm run build

      - name: Build Admin Panel
        run: |
          cd admin-panel
          npm install
          npm run build

      - name: Deploy to Droplet
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DROPLET_IP }}
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
             mkdir -p /var/www/astrocric/website
             mkdir -p /var/www/astrocric/admin-panel
             mkdir -p /var/www/astrocric/backend

      - name: Copy Website Build
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.DROPLET_IP }}
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "website/.next,website/public,website/package.json,website/next.config.mjs"
          target: "/var/www/astrocric/"

      - name: Copy Admin Build
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.DROPLET_IP }}
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "admin-panel/dist"
          target: "/var/www/astrocric/"

      - name: Copy Backend
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.DROPLET_IP }}
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "backend"
          target: "/var/www/astrocric/"

      - name: Finalize Deployment
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DROPLET_IP }}
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
            
            cd /var/www/astrocric/backend && npm install && pm2 restart astrocric-backend || pm2 start server.js --name "astrocric-backend"
            cd /var/www/astrocric/website && npm install --production && pm2 restart astrocric-website || pm2 start npm --name "astrocric-website" -- start
